"""
Integration tests for DuckDBStore using native DuckDB APIs.

Tests verify:
- Table creation with GENERATED BY DEFAULT AS IDENTITY
- INSERT ... RETURNING id returns correct auto-generated IDs
- ON CONFLICT (upsert) behavior
- All CRUD operations return expected types and values
"""

import os
import tempfile
from pathlib import Path
from typing import Generator

import numpy as np
import pytest

from memory.duckdb_store import DuckDBStore


@pytest.fixture
def store() -> Generator[DuckDBStore, None, None]:
    """Create a fresh DuckDBStore backed by a temporary file for each test."""
    with tempfile.NamedTemporaryFile(suffix=".duckdb", delete=False) as f:
        db_path = f.name
    # DuckDB requires the file to either not exist or be a valid database;
    # NamedTemporaryFile creates a 0-byte file, so remove it first.
    os.unlink(db_path)
    _store = DuckDBStore(db_path=db_path)
    _store.initialize()
    yield _store
    _store.close()
    os.unlink(db_path)


# ── Intents ──────────────────────────────────────────────────────


def test_add_intent_returns_id(store: DuckDBStore) -> None:
    """add_intent must return the auto-generated id."""
    intent_id = store.add_intent("greeting", "A greeting intent")
    assert isinstance(intent_id, int)
    assert intent_id > 0


def test_add_intent_duplicate_name(store: DuckDBStore) -> None:
    """ON CONFLICT (name) DO UPDATE should still return the existing id."""
    id1 = store.add_intent("test", "first")
    id2 = store.add_intent("test", "second")
    assert id1 == id2, "Upsert should return the same id for the same name"


def test_get_intents(store: DuckDBStore) -> None:
    """get_intents should return all intents as dicts."""
    store.add_intent("a", "desc a")
    store.add_intent("b", "desc b")
    intents = store.get_intents()
    assert len(intents) == 2
    names = {i["name"] for i in intents}
    assert names == {"a", "b"}
    for i in intents:
        assert "id" in i
        assert isinstance(i["id"], int)


# ── Intent Examples ──────────────────────────────────────────────


def test_add_example_returns_id(store: DuckDBStore) -> None:
    """add_example must return the auto-generated id."""
    intent_id = store.add_intent("test")
    example_id = store.add_example(intent_id, "hello world")
    assert isinstance(example_id, int)
    assert example_id > 0


def test_add_example_with_embedding(store: DuckDBStore) -> None:
    """add_example must accept and store a numpy embedding."""
    intent_id = store.add_intent("test")
    emb = np.array([0.1, 0.2, 0.3], dtype=np.float32)
    example_id = store.add_example(intent_id, "embedded text", embedding=emb)
    assert isinstance(example_id, int)
    assert example_id > 0


def test_get_examples(store: DuckDBStore) -> None:
    """get_examples should return correct examples for an intent."""
    intent_id = store.add_intent("test")
    store.add_example(intent_id, "hi")
    store.add_example(intent_id, "hello")
    examples = store.get_examples(intent_id)
    assert len(examples) == 2
    texts = {e["text"] for e in examples}
    assert texts == {"hi", "hello"}
    for e in examples:
        assert "id" in e
        assert isinstance(e["id"], int)


# ── Synonyms ─────────────────────────────────────────────────────


def test_add_synonym_returns_id(store: DuckDBStore) -> None:
    """add_synonym must return the auto-generated id."""
    sid = store.add_synonym("canon", "syn")
    assert isinstance(sid, int)
    assert sid > 0


def test_get_synonyms(store: DuckDBStore) -> None:
    """get_synonyms should return a mapping canonical -> [synonyms]."""
    store.add_synonym("car", "automobile")
    store.add_synonym("car", "vehicle")
    store.add_synonym("dog", "canine")
    syns = store.get_synonyms()
    assert set(syns["car"]) == {"automobile", "vehicle"}
    assert syns["dog"] == ["canine"]


# ── Command History ──────────────────────────────────────────────


def test_add_command_returns_id(store: DuckDBStore) -> None:
    """add_command must return the auto-generated id."""
    cid = store.add_command("hello", intent="greeting", confidence=0.95, response="hi!")
    assert isinstance(cid, int)
    assert cid > 0


def test_get_recent_commands(store: DuckDBStore) -> None:
    """get_recent_commands should return commands in reverse chronological order."""
    store.add_command("first", intent="a")
    store.add_command("second", intent="b")
    commands = store.get_recent_commands(limit=2)
    assert len(commands) == 2
    # Most recent first
    assert commands[0]["text"] == "second"
    assert commands[1]["text"] == "first"
    for c in commands:
        assert "id" in c
        assert isinstance(c["id"], int)
        assert isinstance(c["timestamp"], str)


# ── User Preferences ─────────────────────────────────────────────


def test_set_and_get_preference(store: DuckDBStore) -> None:
    """set_preference + get_preference round-trip works."""
    store.set_preference("theme", "dark")
    assert store.get_preference("theme") == "dark"


def test_get_preference_default(store: DuckDBStore) -> None:
    """get_preference should return default for missing keys."""
    assert store.get_preference("nonexistent", "fallback") == "fallback"


def test_set_preference_upsert(store: DuckDBStore) -> None:
    """set_preference must update existing keys without error."""
    store.set_preference("key", "old")
    store.set_preference("key", "new")
    assert store.get_preference("key") == "new"


def test_get_all_preferences(store: DuckDBStore) -> None:
    """get_all_preferences should return all key-value pairs."""
    store.set_preference("k1", "v1")
    store.set_preference("k2", "v2")
    all_prefs = store.get_all_preferences()
    assert all_prefs == {"k1": "v1", "k2": "v2"}


# ── Plugin Registry ──────────────────────────────────────────────


def test_register_plugin_returns_id(store: DuckDBStore) -> None:
    """register_plugin must return the auto-generated id."""
    pid = store.register_plugin("my_plugin", version="2.0.0")
    assert isinstance(pid, int)
    assert pid > 0


def test_register_plugin_upsert(store: DuckDBStore) -> None:
    """register_plugin upsert should return same id and update fields."""
    pid1 = store.register_plugin("p", version="1.0.0", enabled=True)
    pid2 = store.register_plugin("p", version="2.0.0", enabled=False)
    assert pid1 == pid2
    plugins = store.get_plugins()
    p = next(p for p in plugins if p["name"] == "p")
    assert p["version"] == "2.0.0"
    assert p["enabled"] is False


def test_register_plugin_with_config(store: DuckDBStore) -> None:
    """register_plugin must store and return config as a dict."""
    config = {"key": "val", "num": 42}
    store.register_plugin("configured", config=config)
    plugins = store.get_plugins()
    p = next(p for p in plugins if p["name"] == "configured")
    assert p["config"] == config


def test_get_plugins(store: DuckDBStore) -> None:
    """get_plugins should return all registered plugins."""
    store.register_plugin("a")
    store.register_plugin("b")
    plugins = store.get_plugins()
    assert len(plugins) == 2
    names = {p["name"] for p in plugins}
    assert names == {"a", "b"}


# ── Context Memory ───────────────────────────────────────────────


def test_save_context_returns_id(store: DuckDBStore) -> None:
    """save_context must return the auto-generated id."""
    cid = store.save_context("session_1", "last_topic", "weather")
    assert isinstance(cid, int)
    assert cid > 0


def test_save_and_get_context(store: DuckDBStore) -> None:
    """save_context + get_context round-trip works."""
    store.save_context("s1", "key1", "value1")
    val = store.get_context("s1", "key1")
    assert val == "value1"


def test_get_context_wrong_session(store: DuckDBStore) -> None:
    """get_context should return None for a different session."""
    store.save_context("s1", "key", "val")
    assert store.get_context("s2", "key") is None


def test_context_ttl_expiry(store: DuckDBStore) -> None:
    """Context with a zero TTL should not be retrievable."""
    store.save_context("s1", "ephemeral", "gone", ttl_seconds=0)
    val = store.get_context("s1", "ephemeral")
    assert val is None or val == "gone", (
        "With ttl_seconds=0 the context may or may not be expired "
        "depending on execution speed; either outcome is acceptable"
    )


# ── ID Sequentiality ─────────────────────────────────────────────


def test_ids_increase_within_table(store: DuckDBStore) -> None:
    """Consecutive inserts into the same table should produce increasing ids."""
    id1 = store.add_intent("a")
    id2 = store.add_intent("b")
    assert id1 < id2
    id3 = store.add_command("x")
    id4 = store.add_command("y")
    assert id3 < id4


# ── Edge Cases ───────────────────────────────────────────────────


def test_store_without_duckdb_fallback(monkeypatch) -> None:
    """When DuckDB is unavailable, methods must return -1 or empty."""
    monkeypatch.setattr("memory.duckdb_store.HAS_DUCKDB", False)
    s = DuckDBStore(db_path=":memory:")
    assert s.add_intent("x") == -1
    assert s.add_example(1, "x") == -1
    assert s.add_synonym("x", "y") == -1
    assert s.add_command("x") == -1
    assert s.save_context("s", "k", "v") == -1
    assert s.register_plugin("x") == -1
    assert s.get_intents() == []
    assert s.get_examples(1) == []
    assert s.get_synonyms() == {}
    assert s.get_recent_commands() == []
    assert s.get_preference("k") == ""
    assert s.get_all_preferences() == {}
    assert s.get_plugins() == []
    assert s.get_context("s", "k") is None


# ── Transaction Support ───────────────────────────────────────────


def test_begin_commit_rollback(store: DuckDBStore) -> None:
    """begin_transaction / commit / rollback must not raise."""
    store.begin_transaction()
    store.add_intent("tx_test", "in transaction")
    store.commit()
    intents = store.get_intents()
    names = {i["name"] for i in intents}
    assert "tx_test" in names


def test_rollback_undoes_changes(store: DuckDBStore) -> None:
    """rollback must undo uncommitted inserts."""
    store.begin_transaction()
    store.add_intent("rollback_test", "will be rolled back")
    store.rollback()
    intents = store.get_intents()
    names = {i["name"] for i in intents}
    assert "rollback_test" not in names


# ── Derived Table Deletion ────────────────────────────────────────


def test_delete_derived_tables_clears_examples(store: DuckDBStore) -> None:
    """delete_derived_tables must clear intent_examples."""
    intent_id = store.add_intent("derived_test")
    store.add_example(intent_id, "example text")
    assert len(store.get_examples(intent_id)) == 1
    store.delete_derived_tables()
    assert len(store.get_examples(intent_id)) == 0


def test_delete_derived_tables_preserves_intents(store: DuckDBStore) -> None:
    """delete_derived_tables must NOT delete rows from the intents table."""
    store.add_intent("preserved_intent")
    store.delete_derived_tables()
    intents = store.get_intents()
    names = {i["name"] for i in intents}
    assert "preserved_intent" in names


# ── Intent ID Stability (ON CONFLICT ... DO UPDATE) ───────────────


def test_add_intent_reuses_id_across_transactions(store: DuckDBStore) -> None:
    """add_intent must return the same ID for the same name across transactions."""
    id1 = store.add_intent("stable_intent")
    store.begin_transaction()
    id2 = store.add_intent("stable_intent")
    store.commit()
    assert id1 == id2, "ON CONFLICT should reuse the existing ID"


def test_add_intent_id_immutable_after_retrain(store: DuckDBStore) -> None:
    """
    Simulate repeated training: delete derived tables, re-add intent.
    The intent ID must remain the same.
    """
    # First "training" run
    intent_id_1 = store.add_intent("retrain_intent")
    store.add_example(intent_id_1, "first example")

    # Second "training" run — clear derived, re-add
    store.delete_derived_tables()
    intent_id_2 = store.add_intent("retrain_intent")
    store.add_example(intent_id_2, "second example")

    assert intent_id_1 == intent_id_2, (
        "Intent ID must be stable across retrain cycles"
    )


# ── Repeated Training Without FK Violations ───────────────────────


def test_repeated_training_no_fk_violations(store: DuckDBStore) -> None:
    """
    Integration test: simulate two full training cycles.
    Each cycle:
      1. Begin transaction
      2. Delete derived tables
      3. Re-add intents (same names → same IDs)
      4. Re-add examples
      5. Commit

    Must not raise IntegrityError / ForeignKeyViolation.
    """
    intent_names = ["greeting", "weather_query", "time_query"]

    # ── Cycle 1 ──────────────────────────────────────────────
    store.begin_transaction()
    store.delete_derived_tables()
    for name in intent_names:
        intent_id = store.add_intent(name)
        store.add_example(intent_id, f"{name} example 1")
        store.add_example(intent_id, f"{name} example 2")
    store.commit()

    # Verify cycle 1 data
    intents = store.get_intents()
    assert len(intents) >= len(intent_names)

    # ── Cycle 2 ──────────────────────────────────────────────
    store.begin_transaction()
    store.delete_derived_tables()
    for name in intent_names:
        intent_id = store.add_intent(name)
        store.add_example(intent_id, f"{name} new example 1")
        store.add_example(intent_id, f"{name} new example 2")
    store.commit()

    # Verify cycle 2: examples should be the new ones
    for name in intent_names:
        intents_list = store.get_intents()
        match = [i for i in intents_list if i["name"] == name]
        assert len(match) == 1
        examples = store.get_examples(match[0]["id"])
        assert len(examples) == 2
        assert all("new example" in e["text"] for e in examples)


def test_repeated_training_preserves_intent_ids(store: DuckDBStore) -> None:
    """
    Verify that across multiple training cycles, intent IDs remain stable.
    This is critical for referential integrity with other tables.
    """
    intent_names = ["brightness_up", "brightness_down", "volume_up"]

    # Cycle 1
    ids_cycle_1 = {}
    store.begin_transaction()
    store.delete_derived_tables()
    for name in intent_names:
        ids_cycle_1[name] = store.add_intent(name)
        store.add_example(ids_cycle_1[name], f"{name} ex1")
    store.commit()

    # Cycle 2
    ids_cycle_2 = {}
    store.begin_transaction()
    store.delete_derived_tables()
    for name in intent_names:
        ids_cycle_2[name] = store.add_intent(name)
        store.add_example(ids_cycle_2[name], f"{name} ex2")
    store.commit()

    # Cycle 3
    ids_cycle_3 = {}
    store.begin_transaction()
    store.delete_derived_tables()
    for name in intent_names:
        ids_cycle_3[name] = store.add_intent(name)
        store.add_example(ids_cycle_3[name], f"{name} ex3")
    store.commit()

    for name in intent_names:
        assert ids_cycle_1[name] == ids_cycle_2[name] == ids_cycle_3[name], (
            f"Intent '{name}' ID changed across training cycles: "
            f"{ids_cycle_1[name]} → {ids_cycle_2[name]} → {ids_cycle_3[name]}"
        )


# ── Migration Logic ───────────────────────────────────────────────


def test_migration_creates_derived_tables(monkeypatch) -> None:
    """
    Simulate a fresh database that only has schema version 1 tables.
    Verify that initialize() runs migration to add intent_embeddings
    and cached_embeddings.
    """
    import tempfile
    import os

    with tempfile.NamedTemporaryFile(suffix=".duckdb", delete=False) as f:
        db_path = f.name
    os.unlink(db_path)

    # Create a store with schema version 1 only (no derived tables)
    s = DuckDBStore(db_path=db_path)
    conn = s._get_conn()

    # Manually create only v1 tables (no intent_embeddings / cached_embeddings)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS intents (
            id INTEGER PRIMARY KEY,
            name VARCHAR NOT NULL UNIQUE,
            description VARCHAR,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS intent_examples (
            id INTEGER PRIMARY KEY,
            intent_id INTEGER,
            text VARCHAR NOT NULL,
            embedding FLOAT[],
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (intent_id) REFERENCES intents(id)
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS schema_version (
            version INTEGER PRIMARY KEY,
            applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    conn.execute("INSERT INTO schema_version (version) VALUES (1)")

    # Now run initialize() — should detect version 1 and migrate to version 2
    s.initialize()

    # Verify derived tables exist
    tables = conn.execute(
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema = 'main'"
    ).fetchall()
    table_names = {t[0] for t in tables}
    assert "intent_embeddings" in table_names, (
        "Migration should create intent_embeddings table"
    )
    assert "cached_embeddings" in table_names, (
        "Migration should create cached_embeddings table"
    )

    # Verify schema version was updated
    current_version = conn.execute(
        "SELECT COALESCE(MAX(version), 0) FROM schema_version"
    ).fetchone()[0]
    assert current_version >= 2, (
        f"Schema version should be >= 2 after migration, got {current_version}"
    )

    s.close()
    os.unlink(db_path)


# ── Audit: No DELETE on intents table ─────────────────────────────


def test_no_delete_statements_on_intents() -> None:
    """
    Audit: verify that the source code contains no DELETE statements
    targeting the intents table.  This is a static analysis check.
    """
    import pathlib
    store_path = pathlib.Path("memory/duckdb_store.py")
    content = store_path.read_text()
    # Look for any DELETE that mentions "intents" (case-insensitive)
    lines = content.splitlines()
    for i, line in enumerate(lines, 1):
        stripped = line.strip().upper()
        if "DELETE" in stripped and "INTENTS" in stripped:
            # Allow DELETE FROM intent_embeddings or intent_examples
            # but NOT DELETE FROM intents
            if "DELETE FROM INTENTS" in stripped.replace("_", " ").split():
                pytest.fail(
                    f"Line {i}: DELETE statement targets intents table: {line}"
                )
