"""
GoalRuntime code templates used by the CODER skill's deterministic path.

The CODER-role model (deepseek-coder-v2:16b) can generate code when a
template does not exist; these deterministic templates cover the common
self-contained cases without any model call.
"""

CALCULATOR_TEMPLATE = '''#!/usr/bin/env python3
"""A small four-operation calculator (generated by Diego's GoalRuntime)."""


def add(a: float, b: float) -> float:
    return a + b


def subtract(a: float, b: float) -> float:
    return a - b


def multiply(a: float, b: float) -> float:
    return a * b


def divide(a: float, b: float) -> float:
    if b == 0:
        raise ZeroDivisionError("cannot divide by zero")
    return a / b


def evaluate(expression: str) -> float:
    """Evaluate a simple 'a OP b' expression safely (no eval)."""
    import re
    m = re.fullmatch(r"\\s*(-?\\d+(?:\\.\\d+)?)\\s*([-+*/])\\s*(-?\\d+(?:\\.\\d+)?)\\s*",
                     expression)
    if not m:
        raise ValueError(f"unsupported expression: {expression!r}")
    a, op, b = float(m.group(1)), m.group(2), float(m.group(3))
    ops = {"+": add, "-": subtract, "*": multiply, "/": divide}
    return ops[op](a, b)


def main() -> None:
    print("Calculator ready. Example: 2 + 2")


if __name__ == "__main__":
    main()
'''

CALCULATOR_TEST_TEMPLATE = '''#!/usr/bin/env python3
"""Tests for the generated calculator."""

from calculator import add, subtract, multiply, divide, evaluate


def test_add():
    assert add(2, 3) == 5


def test_subtract():
    assert subtract(5, 2) == 3


def test_multiply():
    assert multiply(3, 4) == 12


def test_divide():
    assert divide(8, 2) == 4


def test_divide_by_zero():
    try:
        divide(1, 0)
        assert False, "expected ZeroDivisionError"
    except ZeroDivisionError:
        pass


def test_evaluate():
    assert evaluate("2 + 3") == 5
    assert evaluate("10 * 4") == 40
    assert evaluate("9 / 3") == 3
    assert evaluate("7 - 1") == 6


def test_evaluate_rejects_garbage():
    try:
        evaluate("import os")
        assert False, "expected ValueError"
    except ValueError:
        pass
'''

__all__ = ["CALCULATOR_TEMPLATE", "CALCULATOR_TEST_TEMPLATE"]
