#!/usr/bin/env python3
"""A small four-operation calculator (generated by Diego's GoalRuntime)."""


def add(a: float, b: float) -> float:
    return a + b


def subtract(a: float, b: float) -> float:
    return a - b


def multiply(a: float, b: float) -> float:
    return a * b


def divide(a: float, b: float) -> float:
    if b == 0:
        raise ZeroDivisionError("cannot divide by zero")
    return a / b


def evaluate(expression: str) -> float:
    """Evaluate a simple 'a OP b' expression safely (no eval)."""
    import re
    m = re.fullmatch(r"\s*(-?\d+(?:\.\d+)?)\s*([-+*/])\s*(-?\d+(?:\.\d+)?)\s*",
                     expression)
    if not m:
        raise ValueError(f"unsupported expression: {expression!r}")
    a, op, b = float(m.group(1)), m.group(2), float(m.group(3))
    ops = {"+": add, "-": subtract, "*": multiply, "/": divide}
    return ops[op](a, b)


def main() -> None:
    print("Calculator ready. Example: 2 + 2")


if __name__ == "__main__":
    main()
